version: '3'
services:
  web:
    image: httpd
    ports:
      - "80:80"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
    networks:
      - elastic

  fluentd:
    build: ./docker/fluentd
    environment:
      TZ: "America/New_York" # CRITICAL!  fluentd uses localtime as default
    volumes:
      - "./docker/fluentd/conf/fluent.conf:/fluentd/etc/fluent.conf:rw"
#      - "./docker/fluentd/sample_data/syslog:/tmp/syslog:ro"
      - "/var/log/syslog:/tmp/syslog:ro"
      - "./docker/fluentd/sample_data/nginx_access_log_seconds:/tmp/nginx_access_log_seconds:ro"
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - elastic

  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
      container_name: elasticsearch
      environment:
          - discovery.type=single-node
          - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      volumes:
          - ./esdata:/usr/share/elasticsearch/data:rw
      ports:
          - 9200:9200
      labels:
          - co.elastic.logs/module=elasticsearchtmp_cl
          - co.elastic.metrics/module=elasticsearch
      networks:
        - elastic

  kibana:
      image: docker.elastic.co/kibana/kibana:7.9.1
      container_name: kibana
      ports:
          - 5601:5601
      depends_on:
          - elasticsearch
      environment:
          ELASTICSEARCH_URL: http://elasticsearch:9200
          ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      networks:
          - elastic
networks:
    elastic:
      driver: bridge
volumes:
    vibhuviesdata:
      driver: local
